[build-system]
requires = ["setuptools>=70", "wheel", "cython>=3"]
build-backend = "setuptools.build_meta"

[project]
name = "home-utils"
authors = [
    { name = "Jaime Gonzalez Gomez", email = "jgonzg@proton.me" },
]
description = "Collection of personal utils to be used in python development."
requires-python = ">=3.10"
version = "0.1.0"
dependencies = []  # This should always be empty.
license = { text = "MIT license" }
dynamic = ["readme"]

classifiers = [
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "http://github/Jtachan/HomeScripts.git"
Documentation = "https://jtachan.github.io/HomeScripts/"

[tool.setuptools.dynamic]
readme = { file = ["README.md"], content-type = "text/markdown" }

[tool.setuptools.packages.find]
where = ["src"]